// ===== 畫面元素 =====
const moneyText = document.getElementById("money");
const productArea = document.getElementById("productArea");
const undoButton = document.getElementById("undoButton");
const checkoutButton = document.getElementById("checkoutButton");
const clearCurrentSaleButton = document.getElementById("clearCurrentSaleButton");
const currentSaleList = document.getElementById("currentSaleList");
const currentSaleTotal = document.getElementById("currentSaleTotal");
const salesLogList = document.getElementById("salesLogList");
const exportCsvButton = document.getElementById("exportCsvButton");
const resetAllDataButton = document.getElementById("resetAllDataButton");
const startLuckyBagButton = document.getElementById("startLuckyBagButton");
const finishLuckyBagButton = document.getElementById("finishLuckyBagButton");
const luckyBagContentsList = document.getElementById("luckyBagContentsList");
const luckyBagModeText = document.getElementById("luckyBagModeText");
const stockArea = document.getElementById("stockArea");
const cancelLuckyBagButton = document.getElementById("cancelLuckyBagButton");